# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Education
    url: '#education'
    weight: 10
  - name: Publications
    url: '#02_featured'
    weight: 20
  - name: Courses
    url: courses/
    weight: 30
  - name: Hacking
    url: '#hacking'
    weight: 40 
  - name: Projects
    url: '#04_projects'
    weight: 50
  - name: Talks
    url: '#05_talks'
    weight: 60
  - name: Posts
    url: '#06_posts'
    weight: 70
  - name: About me
    url: '#07_experience'
    weight: 80
  - name: Contact
    url: '#08_contact'
    weight: 80
